### ISSUE TITLE
3 migration w/ 3 population Models

### ISSUE THREAD

**Issue by dorozco1504** [sgravel/tracts#10]
Simon

I'm trying to run tracts using a 3-migration pulses model.
Can you provide a driver file to help me with the parameters I should change? I'm having problems with "slices" and "bounds". 

Thanks in advance.

**Comment by sgravel** [comment]
Hi Daniela,
I'm not sure what you need exactly. You are setting up a model with two
populations and three pulses of migration and looking for how to specify
the model?
Simon

**Comment by dorozco1504** [comment]
Sorry, actually I'm interested in using 3 source populations. I correctly ran models with two pulses and 3 populations using the example that you provide. But I got errors when I tried 3 pulses models regarding the numbers of values needed.

**Comment by sgravel** [comment]
I apologize as i just noticed your reply. I still cannot quite address your question as I do not know what errors you are getting. I'm also assuming I am coming much too late. I'll go ahead and close this issue, but let me know if you still need help.
